dist: xenial  # xenial is now the Travis CI default distro
language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

install:
 - pip install tox-travis
script: tox

stages:
  - test

jobs:
  include:
  - python: "3.8"
    env: TOXENV=flake8
